### ISSUE TITLE
Hei

### ISSUE THREAD

**Issue by hakonhagland** [BergenPM/bergenpm.github.io#1]
Hei, jeg er begynt å programmere litt i Perl i det siste. Jeg bor på Nesttun. Kom over siden https://bergenpm.org/ .Bra initiativ, bare ta kontakt hvis det er noe jeg kan hjelpe med. Ha en fin dag!

**Comment by christopherraa** [comment]
Takk for det. Vi har ikke kommet helt i gang enda, men jobber med saken. :) Du finner oss også irc #bergen.pm på irc.perl.org om du vil slå av en prat.
